name: Deploy MkDocs site

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force

